export const FETCH_CSRF_TOKEN = 'FETCH_CSRF_TOKEN';
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const FETCH_CARS = 'FETCH_CARS';
export const ADD_CAR_ACTION = 'ADD_CAR_ACTION';
export const DELETE_CAR_ACTION = 'DELETE_CAR_ACTION';



